export enum Kurikulum {
  MERDEKA = 'Merdeka',
  K13 = 'K-13',
  LOKAL = 'Muatan Lokal'
}

export enum Jenjang {
  SD = 'SD/MI',
  SMP = 'SMP/MTs',
  SMA = 'SMA/MA',
  SMK = 'SMK'
}

export interface GayaMengajar {
  pendekatan_favorit: string; // konstruktivis, langsung, berbasis_proyek, dll
  media_utama: string; // whiteboard, PowerPoint, hands-on, video, dll
  tingkat_interaktivitas: string; // sangat_tinggi, tinggi, sedang, rendah
}

export interface PreferensiKonten {
  gaya_bahasa: string; // formal, semiformal, santai
  panjang_soal: string; // pendek, sedang, panjang
  jenis_soal_favorit: string[]; // PG, esai, isian, uraian, proyek
  konteks_lokal: string; // kota, kabupaten, desa, pesisir, agraris, dll
  nilai_karakter: string[]; // gotong royong, kemandirian, nalar kritis, dll
  contoh_nyata: boolean;
  humor_ringan: boolean;
}

export interface StandarKualitas {
  distribusi_bloom: {
    C1: number;
    C2: number;
    C3: number;
    C4: number;
    C5: number;
    C6: number;
  };
  tingkat_kesulitan_default: 'mudah' | 'sedang' | 'sulit';
  jumlah_soal_default: number;
  format_output_default: string;
}

export interface HistoriPembelajaran {
  topik_sudah_diajarkan: string[];
  topik_yang_sulit_bagi_siswa: string[];
  modul_terbaik_yang_dibuat: string[];
  catatan_kelas: Record<string, string>;
  last_active?: string;
}

export interface ProfilGuru {
  uid: string;
  nama: string;
  mapel: string;
  jenjang: Jenjang;
  kelas: string[];
  kurikulum: Kurikulum;
  sekolah: string;
  kota_provinsi: string;
  tahun_mengajar: number;
  gaya_mengajar: GayaMengajar;
  preferensi_konten: PreferensiKonten;
  standar_kualitas: StandarKualitas;
  histori_pembelajaran?: HistoriPembelajaran;
}

export interface KontenGuru {
  id?: string;
  guru_id: string;
  guru_nama: string;
  tipe: 'modul_ajar' | 'bank_soal' | 'rapor_naratif' | 'admin_autopilot';
  topik: string;
  kelas: string;
  kurikulum: string;
  konten: string; // Markdown generated by Gemini
  created_at: string;
  is_published: boolean;
}

export interface MarketplaceItem {
  id?: string;
  original_guru_id: string;
  original_guru_nama: string;
  original_sekolah: string;
  original_kota: string;
  judul: string;
  mapel: string;
  konten: string;
  tags: string[];
  rating: number;
  remix_count: number;
  downloads_count: number;
  created_at: string;
}

export interface KelasData {
  id?: string;
  guru_id: string;
  kelas_id: string;
  nama_kelas: string;
  daftar_siswa: string[]; // List of student names
  nilai_history: Array<{
    topik: string;
    tanggal: string;
    scores: Record<string, number>; // student_name -> score
  }>;
  laporan_diagnostik: Array<{
    id: string;
    topik: string;
    tanggal: string;
    konten: string; // Analysis markdown result
  }>;
}
